name: 🐞 Bug Report
description: Submit a bug report to help improve SyntaxUi Clone

title: '[BUG]: '

labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Fill in the information below to help us understand and resolve the problem quickly.

  - type: textarea
    attributes:
      label: Description 📝
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Link 🔗
      description: Link to the page where the bug occurred.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots 📸
      description: If applicable, add screenshots to help explain the problem.
    validations:
      required: true
